### ISSUE TITLE
connect not emitting error event if host and port are wrong or not reachable

### ISSUE THREAD

**Issue by kambeena** [InstantWebP2P/node-httpp#11]
Hi,

In connect method, if I give wrong host or port, as per doc error event should be emitted but not happening. The client process gets hanged.

Here is my code:

/**
 * New node file
 */
var udt = require("udts");
var serialize = require('node-serialize');

if (process.argv.length < 4) {
	console.log("Usage: node client_udt_secure host-or-ip port\n ");
	process.exit(-1);
}
var host = process.argv[2];
var port = parseInt(process.argv[3],10);

var cln = udt.connect({host:host, port:port}, function(){
	console.log('UDPs file client connected to '+host+':'+port);
	var data = { action: 'VERIFY', msg:"Hello from client"};
	cln.write(serialize.serialize(data));
	  
});

cln.on('data', function(data){
	commRes = serialize.unserialize(data);
	console.log(commRes.toString());
 });

cln.on('error', function(err){
	 console.log(err);
});

**Comment by sequoiar** [comment]
UDT keep a timeout mechanism,not like TCP .
