### ISSUE TITLE
Unable to build on windows 

### ISSUE THREAD

**Issue by sayantan94** [InstantWebP2P/node-httpp#15]
I am using VS2010 build tools, node version:v6.9.1 , after running the vcbuild command I get the following error:

 Creating library C:\Users\bhowmiks\Experiments\node-httpp\Release\node.lib and object C:\Users\bhowmiks\Experiments\node-httpp\Release\node.exp
  Generating code
 Finished generating code
**LINK : fatal error LNK1123: failure during conversion to COFF: file invalid or corrupt** [C:\Users\bhowmiks\Experiments\node-httpp\node.vcxproj]

**Comment by sequoiar** [comment]
seems vs compatibility issue. refer to  http://stackoverflow.com/questions/10888391/error-link-fatal-error-lnk1123-failure-during-conversion-to-coff-file-inval
