### ISSUE TITLE
Is this being maintained?

### ISSUE THREAD

**Issue by Aaronik** [InstantWebP2P/node-httpp#16]
Hello,

My company desires to use QUIC and this is one of the few projects I can find that makes it available. However, it's built against a version of node that's too old for us to use.

Is this ever going to be rebuilt against a modern version of node? Otherwise, are there any other projects you know about that would allow me to easily use QUIC with node.js?

Thanks for everything you've done,

Aaron

**Comment by sequoiar** [comment]
rebuild with nodejs master branch is in plan.

**Comment by sequoiar** [comment]
planning now.
